// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoWerk.Infrastructure.Persistence;

#nullable disable

namespace TodoWerk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TodoWerkDbContext))]
    [Migration("20260905120751_ApplyMarkersChange")]
    partial class ApplyMarkersChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoWerk.Domain.Changes.Change", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppliedMarkers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("PlannedTaskCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceKeys")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TargetSpelling")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("UndoOfChangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("UndoOfChangeId")
                        .HasDatabaseName("IX_Changes_UndoOfChange")
                        .HasFilter("[UndoOfChangeId] IS NOT NULL");

                    b.HasIndex("State", "RequestedAt")
                        .HasDatabaseName("IX_Changes_State_RequestedAt")
                        .HasFilter("[State] IN ('Pending', 'Running')");

                    b.HasIndex("TenantId", "UserId", "RequestedAt")
                        .HasDatabaseName("IX_Changes_Tenant_User_RequestedAt");

                    b.ToTable("Changes", (string)null);
                });

            modelBuilder.Entity("TodoWerk.Domain.Changes.ChangeJournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GraphTaskId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TaskListId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TitleAfter")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TitleBefore")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("WrittenAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ChangeId", "WrittenAt")
                        .HasDatabaseName("IX_ChangeJournalEntries_Change_WrittenAt");

                    b.ToTable("ChangeJournalEntries", (string)null);
                });

            modelBuilder.Entity("TodoWerk.Domain.Changes.ChangePlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AttemptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ChangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GraphTaskId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Outcome")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PreviewedNewTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PreviewedTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TaskListId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ChangeId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_ChangePlanItems_Change_Sequence");

                    b.HasIndex("ChangeId", "Status")
                        .HasDatabaseName("IX_ChangePlanItems_Change_Status");

                    b.ToTable("ChangePlanItems", (string)null);
                });

            modelBuilder.Entity("TodoWerk.Domain.Indexing.HashtagOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IndexedTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Spelling")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("IndexedTaskId")
                        .HasDatabaseName("IX_HashtagOccurrences_IndexedTask");

                    b.HasIndex("TenantId", "UserId", "Key")
                        .HasDatabaseName("IX_HashtagOccurrences_Tenant_User_Key");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "UserId", "Key"), new[] { "IndexedTaskId", "Spelling" });

                    b.ToTable("HashtagOccurrences", (string)null);
                });

            modelBuilder.Entity("TodoWerk.Domain.Indexing.IndexScan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TaskListId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("WasPreempted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("State", "RequestedAt")
                        .HasDatabaseName("IX_IndexScans_State_RequestedAt")
                        .HasFilter("[State] IN ('Pending', 'Running')");

                    b.HasIndex("TenantId", "UserId", "State")
                        .HasDatabaseName("IX_IndexScans_Tenant_User_State");

                    b.ToTable("IndexScans", (string)null);
                });

            modelBuilder.Entity("TodoWerk.Domain.Indexing.IndexedTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GraphTaskId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TaskListId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId", "GraphTaskId")
                        .IsUnique()
                        .HasDatabaseName("UX_IndexedTasks_Tenant_User_GraphTask");

                    b.HasIndex("TenantId", "UserId", "TaskListId")
                        .HasDatabaseName("IX_IndexedTasks_Tenant_User_TaskList");

                    b.ToTable("IndexedTasks", (string)null);
                });

            modelBuilder.Entity("TodoWerk.Domain.Indexing.TaskListIndexState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeltaLink")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("FailureCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastCompletedScanAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TaskListId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("TasksIndexed")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId", "TaskListId")
                        .IsUnique()
                        .HasDatabaseName("UX_TaskListIndexStates_Tenant_User_TaskList");

                    b.ToTable("TaskListIndexStates", (string)null);
                });

            modelBuilder.Entity("TodoWerk.Domain.Markers.MarkerRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Marker")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("RetiredMarker")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Spelling")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId", "Key")
                        .IsUnique()
                        .HasDatabaseName("UX_MarkerRules_Tenant_User_Key");

                    b.HasIndex("TenantId", "UserId", "Marker")
                        .IsUnique()
                        .HasDatabaseName("UX_MarkerRules_Tenant_User_Marker");

                    b.HasIndex("TenantId", "UserId", "Position")
                        .HasDatabaseName("IX_MarkerRules_Tenant_User_Position");

                    b.ToTable("MarkerRules", (string)null);
                });

            modelBuilder.Entity("TodoWerk.Domain.Onboarding.TenantConsentGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("UX_TenantConsentGrants_Tenant");

                    b.ToTable("TenantConsentGrants", (string)null);
                });

            modelBuilder.Entity("TodoWerk.Domain.Onboarding.TenantMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FirstSignedInAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastSignedInAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("LastSignedInAt")
                        .HasDatabaseName("IX_TenantMembers_LastSignedIn")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_TenantMembers_Tenant");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId"), new[] { "FirstSignedInAt", "LastSignedInAt" });

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_TenantMembers_Tenant_User")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("TenantMembers", (string)null);
                });

            modelBuilder.Entity("TodoWerk.Domain.Changes.ChangeJournalEntry", b =>
                {
                    b.HasOne("TodoWerk.Domain.Changes.Change", null)
                        .WithMany()
                        .HasForeignKey("ChangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoWerk.Domain.Changes.ChangePlanItem", b =>
                {
                    b.HasOne("TodoWerk.Domain.Changes.Change", null)
                        .WithMany()
                        .HasForeignKey("ChangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoWerk.Domain.Indexing.HashtagOccurrence", b =>
                {
                    b.HasOne("TodoWerk.Domain.Indexing.IndexedTask", null)
                        .WithMany()
                        .HasForeignKey("IndexedTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
